export const aa=require('./js.png.png')
export const bb=require('./css.png.png')
export const cc=require('./html.png.png')
export const dd=require('./react.png.png')
export const ee=require('./boot.png')
export const ff=require('./redux.png')
export const gg=require('./rtools.png')
export const hh=require('./vue.png')